import {openDB,getAll,get,put,bulkPut,remove,clearDatabaseData,count} from './db.js';
import {DEFAULT_CATEGORIES,uid,parseLooseNumber,formatMoney,formatDate,escapeHtml,normalizeToPYG,csvEscape,downloadFile,startOfMonthISO,daysInMonth,todayISO} from './utils.js';
import {parseSmartInput} from './parser.js';
import {renderCashflowChart,renderCategoryChart,renderBalanceChart} from './charts.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={transactions:[],categories:[],rates:[],settings:{brlToPyg:1300,baseCurrency:'PYG'},txType:'expense',smartSuggestions:[]};
const els={};
document.addEventListener('DOMContentLoaded',init);

async function init(){mapEls();bind();await openDB();await seed();await reload();els.filterMonth.value=startOfMonthISO();els.txDate.value=todayISO();renderAll();setupConnectivity();registerSW()}
function mapEls(){Object.assign(els,{pageTitle:$('#pageTitle'),transactionDialog:$('#transactionDialog'),transactionForm:$('#transactionForm'),transactionId:$('#transactionId'),txCurrency:$('#txCurrency'),txAmount:$('#txAmount'),txCategory:$('#txCategory'),txDate:$('#txDate'),txDescription:$('#txDescription'),txTags:$('#txTags'),smartImportDialog:$('#smartImportDialog'),smartInput:$('#smartInput'),smartDefaultCurrency:$('#smartDefaultCurrency'),smartSuggestions:$('#smartSuggestions'),filterMonth:$('#filterMonth'),filterType:$('#filterType'),filterCurrency:$('#filterCurrency'),filterCategory:$('#filterCategory'),searchInput:$('#searchInput'),exchangeRate:$('#exchangeRate'),baseCurrency:$('#baseCurrency'),toast:$('#toast')})}
function bind(){
  $$('.nav-link').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$$('[data-view-jump]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.viewJump)));
  $('#newTransactionBtn').addEventListener('click',()=>openTx());$('#quickImportBtn').addEventListener('click',()=>els.smartImportDialog.showModal());
  $$('[data-tx-type]').forEach(b=>b.addEventListener('click',()=>{state.txType=b.dataset.txType;updateTypeTabs()}));els.transactionForm.addEventListener('submit',saveTx);
  [els.filterMonth,els.filterType,els.filterCurrency,els.filterCategory].forEach(x=>x.addEventListener('change',renderTransactions));els.searchInput.addEventListener('input',renderTransactions);
  els.smartInput.addEventListener('input',renderSmart);els.smartDefaultCurrency.addEventListener('change',renderSmart);$('#importSmartBtn').addEventListener('click',importSmart);
  $('#exportJsonBtn').addEventListener('click',exportJSON);$('#importJsonInput').addEventListener('change',importJSON);$('#exportCsvBtn').addEventListener('click',exportCSV);$('#importCsvInput').addEventListener('change',importCSV);$('#clearDatabaseBtn').addEventListener('click',clearDB);
  $('#saveSettingsBtn').addEventListener('click',saveSettings);$('#fetchRateBtn').addEventListener('click',fetchRate);$('#addCategoryBtn').addEventListener('click',addCategory);
  window.editTransaction=editTransaction;window.deleteTransaction=deleteTransaction;window.removeCategory=removeCategory;
}
async function seed(){if(!(await getAll('categories')).length)await bulkPut('categories',DEFAULT_CATEGORIES.map(name=>({name,createdAt:new Date().toISOString()})));if(!(await get('settings','brlToPyg')))await put('settings',{key:'brlToPyg',value:1300});if(!(await get('settings','baseCurrency')))await put('settings',{key:'baseCurrency',value:'PYG'})}
async function reload(){state.transactions=await getAll('transactions');state.categories=(await getAll('categories')).sort((a,b)=>a.name.localeCompare(b.name));state.rates=await getAll('exchangeRates');state.settings.brlToPyg=Number((await get('settings','brlToPyg'))?.value)||1300;state.settings.baseCurrency=(await get('settings','baseCurrency'))?.value||'PYG';els.exchangeRate.value=state.settings.brlToPyg;els.baseCurrency.value=state.settings.baseCurrency;fillCategories()}
function fillCategories(){const opts=state.categories.map(c=>`<option>${escapeHtml(c.name)}</option>`).join('');els.txCategory.innerHTML=opts;els.filterCategory.innerHTML=`<option value="">Todas as categorias</option>${opts}`;renderCategoryManager()}
function switchView(view){$$('.view').forEach(v=>v.classList.remove('active'));$$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$(`#view-${view}`).classList.add('active');els.pageTitle.textContent={dashboard:'Dashboard',transactions:'Transações',analytics:'Analytics',data:'Dados & Backup',settings:'Configurações'}[view]||'Projeto Finanças';if(view==='analytics')renderAnalytics();if(view==='data')renderDBStats()}
function openTx(tx=null){state.txType=tx?.type||'expense';els.transactionId.value=tx?.id||'';els.txCurrency.value=tx?.currency||'PYG';els.txAmount.value=tx?(tx.currency==='PYG'?Math.round(tx.amount).toLocaleString('pt-BR'):Number(tx.amount).toFixed(2).replace('.',',')):'';els.txCategory.value=tx?.category||state.categories[0]?.name||'Outros';els.txDate.value=tx?.date||todayISO();els.txDescription.value=tx?.description||'';els.txTags.value=(tx?.tags||[]).join(', ');$('#transactionDialogTitle').textContent=tx?'Editar transação':'Nova transação';updateTypeTabs();els.transactionDialog.showModal()}
function updateTypeTabs(){$$('[data-tx-type]').forEach(b=>b.classList.toggle('active',b.dataset.txType===state.txType))}
async function saveTx(e){e.preventDefault();const amount=parseLooseNumber(els.txAmount.value);if(!amount){toast('Informe um valor válido.');return}const id=els.transactionId.value||uid(),prev=state.transactions.find(t=>t.id===id);await put('transactions',{id,type:state.txType,currency:els.txCurrency.value,amount:els.txCurrency.value==='PYG'?Math.round(amount):Number(amount.toFixed(2)),category:els.txCategory.value,description:els.txDescription.value.trim()||els.txCategory.value,date:els.txDate.value,tags:els.txTags.value.split(',').map(x=>x.trim()).filter(Boolean),createdAt:prev?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()});els.transactionDialog.close();await reload();renderAll();toast(prev?'Transação atualizada.':'Transação adicionada.')}
function editTransaction(id){const tx=state.transactions.find(t=>t.id===id);if(tx)openTx(tx)}
async function deleteTransaction(id){const tx=state.transactions.find(t=>t.id===id);if(!tx||!confirm(`Excluir "${tx.description}"?`))return;await remove('transactions',id);await reload();renderAll();toast('Transação excluída.')}
function renderAll(){renderDashboard();renderTransactions();renderAnalytics();renderCategoryManager();renderDBStats()}
function monthTx(){const m=startOfMonthISO();return state.transactions.filter(t=>t.date.startsWith(m))}
function totals(list,currency){const income=list.filter(t=>t.currency===currency&&t.type==='income').reduce((s,t)=>s+Number(t.amount),0),expense=list.filter(t=>t.currency===currency&&t.type==='expense').reduce((s,t)=>s+Number(t.amount),0);return{income,expense,balance:income-expense}}
function renderDashboard(){const list=monthTx(),pyg=totals(list,'PYG'),brl=totals(list,'BRL'),rate=state.settings.brlToPyg,base=state.settings.baseCurrency;$('#pygBalance').textContent=formatMoney(pyg.balance,'PYG');$('#pygIncome').textContent=`+ ${formatMoney(pyg.income,'PYG')}`;$('#pygExpense').textContent=`- ${formatMoney(pyg.expense,'PYG')}`;$('#brlBalance').textContent=formatMoney(brl.balance,'BRL');$('#brlIncome').textContent=`+ ${formatMoney(brl.income,'BRL')}`;$('#brlExpense').textContent=`- ${formatMoney(brl.expense,'BRL')}`;const consolidatedPYG=pyg.balance+brl.balance*rate;$('#consolidatedBalance').textContent=formatMoney(base==='PYG'?consolidatedPYG:consolidatedPYG/rate,base);const exp=list.filter(t=>t.type==='expense').reduce((s,t)=>s+normalizeToPYG(t.amount,t.currency,rate),0),now=new Date(),avg=exp/Math.max(now.getDate(),1),projection=avg*daysInMonth(now.getFullYear(),now.getMonth()+1);$('#dailyAverage').textContent=formatMoney(avg,'PYG');$('#projectionText').textContent=`Projeção: ${formatMoney(projection,'PYG')} no mês`;renderRecent();const cash=buildMonthlyCashflow(6),cats=categoryTotals(list);renderCashflowChart($('#cashflowChart'),cash);renderCategoryChart($('#categoryChart'),cats)}
function rowHTML(t){return`<div class="transaction-row"><div class="transaction-main"><strong>${escapeHtml(t.description)}</strong><div class="transaction-meta"><span>${escapeHtml(t.category)}</span><span>${formatDate(t.date)}</span><span>${t.currency}</span>${(t.tags||[]).map(x=>`<span>#${escapeHtml(x)}</span>`).join('')}</div></div><div class="transaction-side"><div class="transaction-value ${t.type==='income'?'income':'expense'}">${t.type==='income'?'+':'-'} ${formatMoney(t.amount,t.currency)}</div><div class="transaction-actions"><button onclick="editTransaction('${t.id}')">Editar</button><button onclick="deleteTransaction('${t.id}')" class="expense">Excluir</button></div></div></div>`}
function renderRecent(){const list=[...state.transactions].sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||'')).slice(0,7);$('#recentTransactions').innerHTML=list.length?list.map(rowHTML).join(''):'<div class="empty">Nenhuma transação registrada.</div>'}
function renderTransactions(){const m=els.filterMonth.value,type=els.filterType.value,currency=els.filterCurrency.value,cat=els.filterCategory.value,q=els.searchInput.value.trim().toLowerCase();const list=[...state.transactions].filter(t=>(!m||t.date.startsWith(m))&&(!type||t.type===type)&&(!currency||t.currency===currency)&&(!cat||t.category===cat)&&(!q||`${t.description} ${(t.tags||[]).join(' ')}`.toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date));$('#transactionCount').textContent=`${list.length} transaç${list.length===1?'ão':'ões'}`;$('#transactionsList').innerHTML=list.length?list.map(rowHTML).join(''):'<div class="empty">Nenhuma transação encontrada.</div>'}
function buildMonthlyCashflow(n){const out=[],now=new Date(),rate=state.settings.brlToPyg;for(let i=n-1;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1),key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`,label=new Intl.DateTimeFormat('pt-BR',{month:'short'}).format(d).replace('.',''),list=state.transactions.filter(t=>t.date.startsWith(key));out.push({label,income:list.filter(t=>t.type==='income').reduce((s,t)=>s+normalizeToPYG(t.amount,t.currency,rate),0),expense:list.filter(t=>t.type==='expense').reduce((s,t)=>s+normalizeToPYG(t.amount,t.currency,rate),0)})}return out}
function categoryTotals(list){const map=new Map(),rate=state.settings.brlToPyg;list.filter(t=>t.type==='expense').forEach(t=>map.set(t.category,(map.get(t.category)||0)+normalizeToPYG(t.amount,t.currency,rate)));return[...map.entries()].map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value)}
function renderAnalytics(){const list=monthTx(),rate=state.settings.brlToPyg,cats=categoryTotals(list);$('#topCategory').textContent=cats[0]?.label||'—';const largest=[...list.filter(t=>t.type==='expense')].sort((a,b)=>normalizeToPYG(b.amount,b.currency,rate)-normalizeToPYG(a.amount,a.currency,rate))[0];$('#largestExpense').textContent=largest?formatMoney(largest.amount,largest.currency):'—';const income=list.filter(t=>t.type==='income').reduce((s,t)=>s+normalizeToPYG(t.amount,t.currency,rate),0),expense=list.filter(t=>t.type==='expense').reduce((s,t)=>s+normalizeToPYG(t.amount,t.currency,rate),0),saving=income>0?(income-expense)/income*100:0;$('#savingsRate').textContent=`${saving.toFixed(1)}%`;const now=new Date(),proj=expense/Math.max(now.getDate(),1)*daysInMonth(now.getFullYear(),now.getMonth()+1);$('#monthProjection').textContent=formatMoney(proj,'PYG');renderRanking(cats);let bal=0;const monthly=new Map();[...state.transactions].sort((a,b)=>a.date.localeCompare(b.date)).forEach(t=>{const v=normalizeToPYG(t.amount,t.currency,rate);bal+=t.type==='income'?v:-v;monthly.set(t.date.slice(0,7),bal)});renderBalanceChart($('#balanceChart'),[...monthly.entries()].map(([label,value])=>({label,value})))}
function renderRanking(cats){const top=cats.slice(0,8),max=top[0]?.value||1;$('#categoryRanking').innerHTML=top.length?top.map(x=>`<div class="rank-item"><strong>${escapeHtml(x.label)}</strong><span>${formatMoney(x.value,'PYG')}</span><div class="rank-bar"><span style="width:${Math.max(4,x.value/max*100)}%"></span></div></div>`).join(''):'<div class="empty">Sem dados de gastos.</div>'}
function renderSmart(){state.smartSuggestions=parseSmartInput(els.smartInput.value,els.smartDefaultCurrency.value);els.smartSuggestions.innerHTML=state.smartSuggestions.length?state.smartSuggestions.map(s=>`<div class="smart-item"><div><strong>${escapeHtml(s.description)}</strong><small>${s.category} · ${s.type==='income'?'Entrada':'Saída'} · ${s.currency}</small></div><strong class="${s.type==='income'?'income':'expense'}">${formatMoney(s.amount,s.currency)}</strong></div>`).join(''):'<div class="empty">Cole anotações para gerar sugestões.</div>'}
async function importSmart(){if(!state.smartSuggestions.length){toast('Nenhuma sugestão para importar.');return}const now=new Date().toISOString(),date=todayISO(),items=state.smartSuggestions.map((s,i)=>({id:uid(),...s,date,createdAt:`${now}-${i}`,updatedAt:now}));await bulkPut('transactions',items);els.smartInput.value='';state.smartSuggestions=[];els.smartImportDialog.close();await reload();renderAll();toast(`${items.length} lançamento(s) importado(s).`)}
async function saveSettings(){state.settings.brlToPyg=Number(els.exchangeRate.value)||1300;state.settings.baseCurrency=els.baseCurrency.value;await put('settings',{key:'brlToPyg',value:state.settings.brlToPyg});await put('settings',{key:'baseCurrency',value:state.settings.baseCurrency});renderAll();toast('Configurações salvas.')}
async function fetchRate(){const b=$('#fetchRateBtn');b.disabled=true;b.textContent='Buscando...';try{const r=await fetch('https://economia.awesomeapi.com.br/json/last/BRL-PYG',{cache:'no-store'});if(!r.ok)throw new Error('API');const data=await r.json(),entry=data.BRLPYG,rate=Number(entry?.bid||entry?.ask||entry?.high);if(!rate)throw new Error('Rate');state.settings.brlToPyg=rate;els.exchangeRate.value=Math.round(rate);await put('settings',{key:'brlToPyg',value:rate});await put('exchangeRates',{id:uid(),pair:'BRL-PYG',rate,date:todayISO(),source:'AwesomeAPI',fetchedAt:new Date().toISOString()});await reload();renderAll();$('#rateStatus').textContent=`Cotação online: 1 BRL ≈ ${Math.round(rate)} PYG`;toast('Cotação atualizada.')}catch(e){console.error(e);toast('Não foi possível buscar a cotação. Use o valor manual.')}finally{b.disabled=false;b.textContent='Buscar cotação online'}}
function renderCategoryManager(){$('#categoryManager').innerHTML=state.categories.map(c=>`<span class="category-chip">${escapeHtml(c.name)}<button onclick="removeCategory('${escapeHtml(c.name)}')">×</button></span>`).join('')}
async function addCategory(){const input=$('#newCategoryInput'),name=input.value.trim();if(!name)return;if(state.categories.some(c=>c.name.toLowerCase()===name.toLowerCase())){toast('Essa categoria já existe.');return}await put('categories',{name,createdAt:new Date().toISOString()});input.value='';await reload();renderAll();toast('Categoria adicionada.')}
async function removeCategory(name){if(state.transactions.some(t=>t.category===name)){toast('A categoria está sendo usada.');return}if(!confirm(`Excluir a categoria "${name}"?`))return;await remove('categories',name);await reload();renderAll();toast('Categoria excluída.')}
function exportJSON(){downloadFile(`projeto-financas-backup-${todayISO()}.json`,JSON.stringify({schemaVersion:3,exportedAt:new Date().toISOString(),transactions:state.transactions,categories:state.categories,settings:state.settings,exchangeRates:state.rates},null,2),'application/json');toast('Backup JSON exportado.')}
async function importJSON(e){const f=e.target.files?.[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!Array.isArray(data.transactions))throw new Error();await bulkPut('transactions',data.transactions);if(Array.isArray(data.categories))await bulkPut('categories',data.categories);if(Array.isArray(data.exchangeRates))await bulkPut('exchangeRates',data.exchangeRates);if(data.settings?.brlToPyg)await put('settings',{key:'brlToPyg',value:data.settings.brlToPyg});if(data.settings?.baseCurrency)await put('settings',{key:'baseCurrency',value:data.settings.baseCurrency});await reload();renderAll();toast('Backup importado.')}catch{alert('Não foi possível importar este JSON.')}finally{e.target.value=''}}
function exportCSV(){const rows=[["id","tipo","moeda","valor","categoria","descricao","tags","data","criado_em","atualizado_em"],...state.transactions.map(t=>[t.id,t.type,t.currency,t.amount,t.category,t.description,(t.tags||[]).join('|'),t.date,t.createdAt||'',t.updatedAt||''])],csv='\ufeff'+rows.map(r=>r.map(csvEscape).join(';')).join('\n');downloadFile(`transacoes-${todayISO()}.csv`,csv,'text/csv;charset=utf-8');toast('CSV exportado.')}
function parseCSVLine(line){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===';'&&!q){out.push(cur);cur=''}else cur+=c}out.push(cur);return out}
async function importCSV(e){const f=e.target.files?.[0];if(!f)return;try{const lines=(await f.text()).replace(/^\ufeff/,'').split(/\r?\n/).filter(Boolean),header=parseCSVLine(lines[0]),idx=Object.fromEntries(header.map((h,i)=>[h.trim().toLowerCase(),i])),items=[];for(const line of lines.slice(1)){const r=parseCSVLine(line),currency=r[idx.moeda]||'PYG',amount=Number(String(r[idx.valor]||'0').replace(',','.'));if(!amount)continue;items.push({id:r[idx.id]||uid(),type:r[idx.tipo]||'expense',currency,amount:currency==='PYG'?Math.round(amount):Number(amount.toFixed(2)),category:r[idx.categoria]||'Outros',description:r[idx.descricao]||'Importado',tags:String(r[idx.tags]||'').split('|').filter(Boolean),date:r[idx.data]||todayISO(),createdAt:r[idx.criado_em]||new Date().toISOString(),updatedAt:r[idx.atualizado_em]||new Date().toISOString()})}await bulkPut('transactions',items);await reload();renderAll();toast(`${items.length} transação(ões) importada(s).`)}catch{alert('Não foi possível importar este CSV.')}finally{e.target.value=''}}
async function clearDB(){if(!confirm('Apagar TODOS os dados financeiros locais?'))return;await clearDatabaseData();await seed();await reload();renderAll();toast('Banco local limpo.')}
async function renderDBStats(){$('#dbTransactions').textContent=await count('transactions');$('#dbCategories').textContent=await count('categories');$('#dbRates').textContent=await count('exchangeRates')}
function setupConnectivity(){const update=()=>$('#onlineStatus').textContent=navigator.onLine?'Online':'Offline';window.addEventListener('online',update);window.addEventListener('offline',update);update()}
async function registerSW(){if('serviceWorker'in navigator&&location.protocol.startsWith('http'))try{await navigator.serviceWorker.register('./sw.js')}catch(e){console.warn(e)}}
let toastTimer;function toast(msg){clearTimeout(toastTimer);els.toast.textContent=msg;els.toast.classList.add('show');toastTimer=setTimeout(()=>els.toast.classList.remove('show'),2200)}
